default: &default
  adapter: postgis
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 10 } %>
  host: <%= ENV.fetch('PG_HOST', 'localhost') %>
  port: <%= ENV.fetch('PG_PORT', '5432') %>
  username: <%= ENV.fetch('PG_USER', 'sipario') %>
  password: <%= ENV.fetch('PG_PASSWORD', 'sipario') %>
  encoding: unicode
  schema_search_path: public

development:
  <<: *default
  database: sipario_development

test:
  <<: *default
  database: sipario_test

production:
  primary: &primary_production
    <<: *default
    database: sipario_production
    username: sipario
    password: <%= ENV["POSTGRES_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: sipario_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: sipario_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: sipario_production_cable
    migrations_paths: db/cable_migrate
